[workspace]
resolver = "2"
members = [
    "keystone-server",
    "keystone-core",
    "keystone-client",
    "xtask",
]

[workspace.package]
edition = "2024"
version = "0.2.0"
authors = ["iris8721"]
license = "MIT"
repository = "https://github.com/iris8721/keystone"
readme = "README.md"
keywords = ["licensing", "authentication", "mtls", "ed25519", "session"]
categories = ["authentication", "cryptography"]

[profile.dev]
opt-level = 1
debug = true
overflow-checks = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = true
strip = false
