[package]
name = "keystone-client"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
keystone-core = { path = "../keystone-core" }
chrono = { version = "0.4", features = ["serde"] }
ed25519-dalek = "2"
hex = "0.4"
rand = "0.8"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
rustls = { version = "0.23", features = ["ring"] }
rustls-pemfile = "2"
rustls-pki-types = "1"
rustls-webpki = "0.103"
serde = { version = "1", features = ["derive"] }
serde-big-array = "0.5"
serde_json = "1"
sha2 = "0.10"
thiserror = "1"
uuid = { version = "1", features = ["v4", "serde"] }

[dev-dependencies]
axum = "0.7"
axum-server = { version = "0.7", features = ["tls-rustls"] }
keystone-server = { path = "../keystone-server" }
rcgen = "0.13"
sha2 = "0.10"
tokio = { version = "1", features = ["full"] }
